version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: gra-dev
    network_mode: host
    privileged: true
    volumes:
      - ..:/root/gra
      - ./.bashrc:/root/.bashrc
      - ./convenience.sh:/root/convenience.sh
      - /root/catkin_ws/.catkin_tools
      - /root/catkin_ws/build
      - /root/catkin_ws/devel
      - /root/catkin_ws/install
      - /root/catkin_ws/logs
      - /root/.dev
      - /root/.bash_history
      - ./.ssh:/root/.ssh
      - ./sshd_config:/etc/ssh/sshd_config
      - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
      - '$HOME/.Xauthority:/root/.Xauthority:rw'
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /root/.penv
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/dri
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/media0
      - /dev/media1
      - /dev/media2
      - /dev/media3
      - /dev/video0
      - /dev/video1
      - /dev/video2
      - /dev/video3
      - /dev/video4
      - /dev/video5
      - /dev/video6
      - /dev/video7
      - /dev/video8
      - /dev/video9
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - HOST_OS=linux
    entrypoint: tail -f /dev/null
    # Uncomment the following if device is cuda compatible to allow gpu acceleration

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
