# em_3905_joint_ctrlr_params.yaml


# Publish the joint states to joint_states.
joint_state_ctrlr:
  type: joint_state_controller/JointStateController
  publish_rate: 30

left_steering_ctrlr:
  joint: left_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 15.0, i: 0.0, d: 1.0}
right_steering_ctrlr:
  joint: right_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 15.0, i: 0.0, d: 1.0}

left_front_axle_ctrlr:
  joint: left_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
right_front_axle_ctrlr:
  joint: right_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
left_rear_axle_ctrlr:
  joint: left_rear_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
right_rear_axle_ctrlr:
  joint: right_rear_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}

# The proportional gain of each shock absorber controller is
# 2 * (shock_stroke * shock_spring_constant / wheel_travel). shock_stroke is
# 0.028575 m. shock_spring_constant, an approximation of a Traxxas Ultra Shock
# shock absorber spring's constant, is 437.817 N/m. wheel_travel, defined in
# em_3905.urdf.xacro, is 0.084 m.
#
# The derivative gain of each shock absorber controller is 2 * shock_damping.
# shock_damping, an approximation of the viscous damping coefficient of an
# Ultra Shock shock absorber, is 36.2416 Ns/m
# (i.e. sqrt(3 * shock_spring_constant)).

  # left_front_shock_ctrlr:
  #   joint: left_front_shock
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 297.8719, i: 0.0, d: 72.4832}
  # right_front_shock_ctrlr:
  #   joint: right_front_shock
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 297.8719, i: 0.0, d: 72.4832}
  # left_rear_shock_ctrlr:
  #   joint: left_rear_shock
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 297.8719, i: 0.0, d: 72.4832}
  # right_rear_shock_ctrlr:
  #   joint: right_rear_shock
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 297.8719, i: 0.0, d: 72.4832}
left_front_shock_ctrlr:
  joint: left_front_shock
  type: effort_controllers/JointPositionController
  pid: {p: 1, i: 0.0, d: 1}
right_front_shock_ctrlr:
  joint: right_front_shock
  type: effort_controllers/JointPositionController
  pid: {p: 1, i: 0.0, d: 1}
left_rear_shock_ctrlr:
  joint: left_rear_shock
  type: effort_controllers/JointPositionController
  pid: {p: 1, i: 0.0, d: 1}
right_rear_shock_ctrlr:
  joint: right_rear_shock
  type: effort_controllers/JointPositionController
  pid: {p: 1, i: 0.0, d: 1}
